server {
    listen 80;
    server_name lumina.a4ivi4.dev;
    server_tokens off;

    # Docker internal DNS resolver
    resolver 127.0.0.11 valid=30s;
    
    location /ws {
        set $upstream http://signal-server:3000;
        proxy_pass $upstream/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
